{{- $config := fromYaml (include "components" .) }}
{{- if $config.nodeAgent.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nodeAgent.name }}
  namespace: {{ .Values.ksNamespace }}
data:
  config.json: |
    {
        "relevantCVEServiceEnabled": true,
        "InitialDelay": "{{ .Values.nodeAgent.config.learningPeriod }}",
        "updateDataPeriod": "{{ .Values.nodeAgent.config.updatePeriod }}",
        "maxSniffingTimePerContainer": "{{ .Values.nodeAgent.config.maxLearningPeriod }}"
    }
{{- end }}
