{{- $config := fromYaml (include "components" .) }}
{{- if $config.nodeAgent.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.nodeAgent.name }}
  namespace: {{ .Values.ksNamespace }}
{{- end }}
